nelmio_cors:
    defaults:
        allow_origin:
            - 'http://localhost:3000'
            - 'https://blog-frontend-two-lac.vercel.app'
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin:
                - 'http://localhost:3000'
                - 'https://blog-frontend-two-lac.vercel.app'
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']